feat(branch-utilities): added branchName and isPr override via ENV
shiftcode/sc-commons-public pull request #31
Opened 2024-07-12 09:36 UTC by patricksuter

2024-07-12 10:35 UTC, michaelwittwer requested changes
Implementation looks good. Just some typos.

2024-07-12 10:35 UTC, michaelwittwer commented on packages/branch-utilities/src/lib/types/sc-override-env-var.type.ts
> +  /** flag to override isPr getBranchInfo(), needs to be used in conjunction with SC_OVERRIDE_IS_PR */
...with SC_OVERRIDE_BRANCH_NAME

2024-07-12 10:35 UTC, michaelwittwer commented on packages/branch-utilities/src/lib/base.utils.ts
> +    // full branch name override via en vars SC_OVERRIDE_BRANCH_NAME and SC_OVERRIDE_IS_PR
en -> env

2024-07-12 12:33 UTC, patricksuter commented on packages/branch-utilities/src/lib/types/sc-override-env-var.type.ts
> +  /** flag to override isPr getBranchInfo(), needs to be used in conjunction with SC_OVERRIDE_IS_PR */
thx, I changed it

2024-07-15 07:48 UTC, michaelwittwer approved these changes

2024-07-22 07:51 UTC, michaelwittwer commented
@patricksuter Anything blocking this from being merged?

2024-07-26 13:23 UTC, merged